name: Metrics
on:
  # Schedule daily updates
  schedule: [{ cron: "0 0 * * *" }]
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: { branches: ["master", "main"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: idimetrix
          config_timezone: America/New_York
          #          config_display: columns  # display information in columns
          committer_message: "chore: update metrics"
          template: classic
          base: header, activity, community, repositories, metadata # base content (user information)
          plugin_introduction: yes # general information about the account
          #          plugin_sponsors: yes

          plugin_isocalendar: yes # 3D isometric calendar
          plugin_isocalendar_duration: full-year # shows activity for the entire year

          plugin_languages: yes # display used programming languages
          plugin_languages_details: bytes-size, percentage # additional code info: size and percentage

          plugin_achievements: yes

          plugin_achievements_threshold: X # (shows achievement badges that are not yet unlocked)
          plugin_achievements_display: detailed # detailed description of achievement badges

          plugin_calendar: yes # displays activity by years, starting from the current year
          plugin_calendar_limit: 11 # shows activity for this many years

          plugin_habits: yes # daily and weekly activity
          plugin_habits_facts: yes # displays analysis of weekly activity
          plugin_habits_charts: yes # displays characteristics

          plugin_licenses: yes # license information
          plugin_licenses_setup: npm ci # detailed information about licenses used

          plugin_skyline: yes # 3D skyline activity plugin
          plugin_skyline_year: 2022 # for which year
          plugin_skyline_frames: 120 # number of frames
          plugin_skyline_quality: 1 # quality level 1 - best

          plugin_stargazers: yes # monthly activity
          plugin_stargazers_charts_type: chartist # activity type - smooth lines

          plugin_support: yes # support plugin

          plugin_topics: yes # plugin for used topics
          plugin_topics_limit: 0
          plugin_topics_mode: icons
